/**
 * exportPDF — Generates a clean, printable HTML page and triggers browser print dialog.
 * Fixes the "stays in coded form" bug by using proper DOCTYPE, charset, print CSS.
 *
 * Usage:
 *   import { exportPDF } from '@/lib/utils/export-pdf';
 *   exportPDF({ title: 'My Document', sections: [{ heading: 'Chapter 1', content: 'Text here' }] });
 */

export function exportPDF({ title = 'Syllabrix Document', sections = [], footer = 'Syllabrix · syllabrix.com' }) {
  const win = window.open('', '_blank');
  if (!win) {
    // Popup blocked — fallback to same window
    alert('Please allow popups for PDF export');
    return;
  }

  const sectionHTML = sections.map(s => {
    if (typeof s === 'string') return `<p style="margin-bottom:10px;line-height:1.7">${s}</p>`;
    return `
      ${s.heading ? `<h2 style="font-size:14px;color:#4F46E5;margin:18px 0 8px;font-weight:700;border-bottom:1px solid #E5E7EB;padding-bottom:4px">${s.heading}</h2>` : ''}
      ${s.content ? `<p style="margin-bottom:8px;line-height:1.7;font-size:12px;color:#374151">${s.content}</p>` : ''}
      ${s.list ? `<ul style="margin:6px 0 12px 20px;font-size:12px;color:#374151">${s.list.map(i => `<li style="margin-bottom:4px;line-height:1.6">${i}</li>`).join('')}</ul>` : ''}
      ${s.table ? renderTable(s.table) : ''}
    `;
  }).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    @page { size: A4; margin: 20mm; }
    body {
      font-family: 'Segoe UI', 'Noto Sans', system-ui, sans-serif;
      padding: 40px;
      color: #1e293b;
      max-width: 800px;
      margin: 0 auto;
      line-height: 1.6;
      font-size: 12px;
    }
    h1 {
      font-size: 20px;
      color: #4F46E5;
      margin-bottom: 6px;
      font-weight: 800;
    }
    .subtitle {
      font-size: 11px;
      color: #94a3b8;
      margin-bottom: 20px;
    }
    .footer {
      margin-top: 30px;
      border-top: 1px solid #e2e8f0;
      padding-top: 12px;
      font-size: 10px;
      color: #94a3b8;
      text-align: center;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 10px 0;
      font-size: 11px;
    }
    th, td {
      border: 1px solid #e2e8f0;
      padding: 6px 10px;
      text-align: left;
    }
    th { background: #f1f5f9; font-weight: 600; color: #475569; }
    .katex { font-size: 1.1em; }
    @media print {
      body { padding: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="text-align:center;margin-bottom:20px;padding:10px;background:#f1f5f9;border-radius:8px">
    <button onclick="window.print()" style="padding:8px 24px;background:#4F46E5;color:white;border:none;border-radius:6px;font-weight:700;cursor:pointer;font-size:13px">
      🖨️ Print / Save as PDF
    </button>
    <p style="font-size:10px;color:#94a3b8;margin-top:6px">Use "Save as PDF" in print dialog</p>
  </div>
  <h1>${title}</h1>
  <p class="subtitle">Generated by Syllabrix · ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
  ${sectionHTML}
  <div class="footer">${footer}</div>
</body>
</html>`;

  win.document.write(html);
  win.document.close();

  // Auto-trigger print after content loads
  win.onload = () => {
    setTimeout(() => win.print(), 500);
  };
}

function renderTable(data) {
  if (!data || !data.headers || !data.rows) return '';
  return `<table>
    <thead><tr>${data.headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
    <tbody>${data.rows.map(row => `<tr>${row.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody>
  </table>`;
}

/**
 * Quick export — just text content
 */
export function exportTextAsPDF(title, text) {
  exportPDF({
    title,
    sections: text.split('\n\n').map(p => p.trim()).filter(Boolean).map(p => ({ content: p })),
  });
}

export default exportPDF;
