const APP_CONFIG = {
  DEFAULT_PAGE_SIZE: 20, MAX_PAGE_SIZE: 50,
  MAX_POST_LENGTH: 5000, MAX_COMMENT_LENGTH: 1000,
  MAX_MEDIA_PER_POST: 5, MAX_HASHTAGS_PER_POST: 10,
  MAX_BIO_LENGTH: 500, MAX_SKILLS: 20, MAX_INTERESTS: 15,
  MAX_MESSAGE_LENGTH: 2000, MAX_GROUP_MEMBERS: 100, MAX_GROUP_NAME_LENGTH: 100,
  MAX_IMAGE_SIZE_MB: 5, MAX_VIDEO_SIZE_MB: 50, MAX_DOCUMENT_SIZE_MB: 10,
  MAX_JOB_TITLE_LENGTH: 200, MAX_JOB_DESCRIPTION_LENGTH: 5000,
  MAX_COVER_MESSAGE_LENGTH: 2000,
  MIN_PASSWORD_LENGTH: 8, MAX_PASSWORD_LENGTH: 128,
  JWT_EXPIRY_DAYS: 7, MAX_LOGIN_ATTEMPTS: 5, LOCKOUT_DURATION_MINUTES: 30,
  RATE_LIMIT_WINDOW_MINUTES: 15, RATE_LIMIT_MAX_REQUESTS: 100,
  XP_PER_ACTIVITY_BASE: 10, XP_PER_TEAM_ACTIVITY: 15, MAX_TEAM_SIZE: 6,
  MIN_USERNAME_LENGTH: 3, MAX_USERNAME_LENGTH: 30,
};
module.exports = { APP_CONFIG };
