import api from '../api-client';

export const aiAPI = {
  // ═══ CURRENT AFFAIRS ═══
  getCurrentAffairs: (date) => api.get('/ai/current-affairs', { params: { date } }),
  getAffairsRange: (days) => api.get('/ai/current-affairs/range', { params: { days } }),
  generateAffairs: (date) => api.post('/ai/current-affairs/generate', { date }),

  // ═══ CURRICULUM DRILL-DOWN — NEW ═══
  getSubjects: (classLevel) =>
    api.get('/ai/curriculum/subjects', { params: { class_level: classLevel } }),
  getChapters: (classLevel, board, subject) =>
    api.get('/ai/curriculum/chapters', { params: { class_level: classLevel, board, subject } }),
  getTopics: (classLevel, board, subject, chapter) =>
    api.get('/ai/curriculum/topics', { params: { class_level: classLevel, board, subject, chapter } }),

  // ═══ MIND MAP ═══
  generateMindMap: (topic, depth, options = {}) =>
    api.post('/ai/mindmap', { topic, depth, ...options }),

  // ═══ MIND MAP NOTES ═══
  generateMindMapNotes: (topic, options = {}) =>
    api.post('/ai/mindmap/notes', { topic, ...options }),

  // ═══ FLOWCHART — NEW ═══
  generateFlowchart: (topic, options = {}) =>
    api.post('/ai/mindmap/flowchart', { topic, ...options }),

  // ═══ DOUBT WITH DIAGRAM — NEW ═══
  explainWithDiagram: (question, options = {}) =>
    api.post('/ai/mindmap/explain', { question, ...options }),

  // ═══ CAREER GUIDANCE ═══
  getStreamGuidance: (stream, interests, currentClass) =>
    api.post('/ai/career/guidance', { stream, interests, current_class: currentClass }),
  compareStreams: (stream1, stream2, interests) =>
    api.post('/ai/career/compare', { stream1, stream2, interests }),
  careerChat: (history, message) =>
    api.post('/ai/career/chat', { history, message }),

  // ═══ EXAM DETAILS ═══
  getExamDetails: (examName) =>
    api.get('/ai/exam-details', { params: { exam_name: examName } }),

  // ═══ DOUBT CLEARING ═══
  clearDoubt: (question, context) =>
    api.post('/ai/doubt', { question, context }),
  doubtChat: (history, message, subject) =>
    api.post('/ai/doubt/chat', { history, message, subject }),

  // ═══ AI BUDDY — PERSISTENT CHAT — NEW ═══
  buddyChat: (message, sessionId, options = {}) =>
    api.post('/ai/buddy/chat', { message, session_id: sessionId, ...options }),

  // ═══ SESSION MANAGEMENT — NEW ═══
  createSession: (sessionType, title, subject) =>
    api.post('/ai/chat/sessions', { session_type: sessionType, title, subject }),
  deleteSession: (sessionId) =>
    api.delete(`/ai/chat/sessions/${sessionId}`),
  updateSessionTitle: (sessionId, title) =>
    api.put(`/ai/chat/sessions/${sessionId}`, { title }),

  // ═══ CHAT HISTORY ═══
  getChatSessions: (type) =>
    api.get('/ai/chat/sessions', { params: { type } }),
  getChatMessages: (sessionId) =>
    api.get(`/ai/chat/sessions/${sessionId}/messages`),

  // ═══ AI EXPERIENCE LAB ═══
  getAISectors: () => api.get('/ai/experience/sectors'),
  exploreProfession: (profession) =>
    api.get('/ai/experience/explore', { params: { profession } }),
  generateChallenge: (profession, level) =>
    api.post('/ai/experience/challenge', { profession, level }),
  getProfessionalComms: (profession) =>
    api.get('/ai/experience/comms', { params: { profession } }),

  // ═══ MILESTONE 2 — NEWSROOM ═══
  getNewsroom: (params) => api.get('/ai/newsroom', { params }),
  generateNewsroom: (date, category) =>
    api.post('/ai/newsroom/generate', { date, category }),
  expandArticle: (headline, category) =>
    api.post('/ai/newsroom/expand', { headline, category }),
  getMonthlyCompilation: (year, month) =>
    api.get('/ai/newsroom/monthly', { params: { year, month } }),
  getNewsSources: () => api.get('/ai/newsroom/sources'),
  getNewsCategories: () => api.get('/ai/newsroom/categories'),

  // ═══ MILESTONE 2 — AUTO QUIZ GENERATOR ═══
  autoGenerateDailyQuiz: (date) =>
    api.post('/ai/quiz/generate-daily', { date }),
  generateTopicQuiz: (topic, options = {}) =>
    api.post('/ai/quiz/generate-topic', { topic, ...options }),
  generateWeeklyChallenge: () =>
    api.post('/ai/quiz/generate-weekly'),

  // ═══ MILESTONE 2 — STREAM NAVIGATOR ═══
  getAptitudeQuestions: () => api.get('/ai/navigator/aptitude-questions'),
  submitAptitudeAssessment: (answers, options = {}) =>
    api.post('/ai/navigator/aptitude', { answers, ...options }),
  generateAlignmentReport: (studentData, parentData) =>
    api.post('/ai/navigator/alignment', { student_data: studentData, parent_data: parentData }),
  generateCareerRoadmap: (career, options = {}) =>
    api.post('/ai/navigator/roadmap', { career, ...options }),

  // ═══ MILESTONE 5 — VIRTUAL LAB ═══
  getLabSubjects: () => api.get('/ai/lab/subjects'),
  getLabExperiments: (subject, classLevel) =>
    api.get('/ai/lab/experiments', { params: { subject, class_level: classLevel } }),
  generateExperiment: (subject, experiment, options = {}) =>
    api.post('/ai/lab/experiment', { subject, experiment, ...options }),
  getLabVisualization: (experiment, step) =>
    api.get('/ai/lab/visualization', { params: { experiment, step } }),

  // ═══ MILESTONE 5 — MOCK INTERVIEW ═══
  getInterviewTypes: () => api.get('/ai/interview/types'),
  startInterview: (type, options = {}) =>
    api.post('/ai/interview/start', { type, ...options }),
  evaluateInterviewAnswer: (type, question, answer, history) =>
    api.post('/ai/interview/evaluate', { type, question, answer, history }),
  getInterviewReport: (type, history) =>
    api.post('/ai/interview/report', { type, history }),

  // ═══ MILESTONE 5 — DEBATE ARENA ═══
  getDebateCategories: () => api.get('/ai/debate/categories'),
  getTrendingDebateTopics: () => api.get('/ai/debate/trending'),
  generateDebateTopic: (category, options = {}) =>
    api.post('/ai/debate/topic', { category, ...options }),
  debateRespond: (topic, studentSide, argument, history) =>
    api.post('/ai/debate/respond', { topic, student_side: studentSide, argument, history }),
  evaluateDebate: (topic, studentSide, history) =>
    api.post('/ai/debate/evaluate', { topic, student_side: studentSide, history }),
};
