'use client';
import { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { aiAPI } from '@/lib/api/ai.api';
import { exportPDF } from '@/lib/utils/export-pdf';
import {
  FileText, Loader2, Sparkles, Download, Printer, RotateCcw,
  BookOpen, GraduationCap, Settings, CheckCircle
} from 'lucide-react';
import toast from 'react-hot-toast';

const BOARDS = ['CBSE', 'ICSE', 'State Board', 'IB'];
const CLASSES = ['6', '7', '8', '9', '10', '11', '12'];
const SUBJECTS = {
  '6': ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
  '7': ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
  '8': ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
  '9': ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
  '10': ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
  '11': ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English', 'Economics', 'Accountancy', 'Computer Science'],
  '12': ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English', 'Economics', 'Accountancy', 'Computer Science'],
};

export default function QuestionPaperPage() {
  const { user } = useAuth();
  const [form, setForm] = useState({
    class_level: user?.profile?.class_name?.toString().replace(/\D/g, '') || '10',
    board: user?.profile?.board || 'CBSE',
    subject: 'Mathematics',
    chapters: '',
    difficulty: 'medium',
    duration: '3 hours',
    total_marks: '80',
  });
  const [paper, setPaper] = useState(null);
  const [loading, setLoading] = useState(false);

  const update = (k, v) => setForm(p => ({ ...p, [k]: v }));

  const generatePaper = async () => {
    setLoading(true); setPaper(null);
    try {
      const prompt = `Generate a complete question paper for:
Class: ${form.class_level}
Board: ${form.board}
Subject: ${form.subject}
${form.chapters ? `Chapters: ${form.chapters}` : 'Full syllabus'}
Difficulty: ${form.difficulty}
Duration: ${form.duration}
Total Marks: ${form.total_marks}

Return ONLY JSON:
{
  "title": "${form.board} Class ${form.class_level} ${form.subject}",
  "subtitle": "Practice Question Paper",
  "duration": "${form.duration}",
  "total_marks": ${form.total_marks},
  "instructions": ["Answer all questions", "Show all working for math problems"],
  "sections": [
    {
      "name": "Section A — MCQ (1 mark each)",
      "marks": 20,
      "questions": [
        { "q_no": 1, "question": "Full question text", "marks": 1, "type": "mcq", "options": ["A) ...", "B) ...", "C) ...", "D) ..."] }
      ]
    },
    {
      "name": "Section B — Short Answer (2 marks each)",
      "marks": 20,
      "questions": [
        { "q_no": 11, "question": "Full question text", "marks": 2, "type": "short" }
      ]
    },
    {
      "name": "Section C — Long Answer (5 marks each)",
      "marks": 25,
      "questions": [
        { "q_no": 21, "question": "Full question text with parts (a), (b)", "marks": 5, "type": "long" }
      ]
    }
  ]
}

Make questions NCERT-aligned for ${form.board}. Use proper math notation with $ delimiters for LaTeX. Include at least 25 questions. Make it realistic like an actual board exam paper. ONLY valid JSON.`;

      const res = await aiAPI.buddyChat(prompt, null, { class_level: form.class_level });
      const reply = res.data?.data?.reply || res.data?.data;
      try {
        const parsed = JSON.parse(typeof reply === 'string' ? reply.replace(/```json|```/g, '').trim() : JSON.stringify(reply));
        setPaper(parsed);
      } catch { setPaper({ raw: reply }); }
    } catch { toast.error('Could not generate paper'); }
    finally { setLoading(false); }
  };

  const downloadPDF = () => {
    if (!paper || paper.raw) return;
    const sections = [];
    sections.push({ content: `<strong>Time: ${paper.duration} | Max Marks: ${paper.total_marks}</strong>` });
    if (paper.instructions) {
      sections.push({ heading: 'General Instructions', list: paper.instructions });
    }
    paper.sections?.forEach(sec => {
      sections.push({ heading: `${sec.name} (${sec.marks} marks)` });
      sec.questions?.forEach(q => {
        let qText = `<strong>Q${q.q_no}.</strong> ${q.question} <span style="color:#6366F1">[${q.marks} marks]</span>`;
        if (q.options) qText += '<br/>' + q.options.join('<br/>');
        sections.push({ content: qText });
      });
    });
    exportPDF({ title: paper.title || 'Question Paper', sections, footer: `${paper.subtitle || 'Practice Paper'} · Generated by Syllabrix` });
  };

  return (
    <div className="max-w-3xl mx-auto space-y-5">
      {/* Hero */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-indigo-700 via-blue-700 to-cyan-700 p-6">
        <div className="absolute top-0 right-0 w-72 h-72 bg-cyan-400/10 rounded-full -translate-y-1/2 translate-x-1/3" />
        <div className="absolute top-5 right-10 text-3xl">📝</div>
        <div className="relative z-10 flex items-start gap-4">
          <div className="w-12 h-12 rounded-2xl bg-white/10 backdrop-blur-sm border border-white/10 flex items-center justify-center flex-shrink-0"><FileText size={24} className="text-cyan-200" /></div>
          <div><h1 className="text-xl font-extrabold text-white tracking-tight">Question Paper Generator</h1>
          <p className="text-blue-200/70 text-sm mt-0.5">AI generates practice papers — NCERT-aligned, board-specific, print-ready</p></div>
        </div>
      </div>

      {/* Form */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-[0_1px_2px_rgba(0,0,0,0.1)] p-5 space-y-4">
        <div className="grid sm:grid-cols-3 gap-3">
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Class</label>
            <select value={form.class_level} onChange={e => update('class_level', e.target.value)}
              className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20">
              {CLASSES.map(c => <option key={c} value={c}>Class {c}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Board</label>
            <select value={form.board} onChange={e => update('board', e.target.value)}
              className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20">
              {BOARDS.map(b => <option key={b} value={b}>{b}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Subject</label>
            <select value={form.subject} onChange={e => update('subject', e.target.value)}
              className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20">
              {(SUBJECTS[form.class_level] || SUBJECTS['10']).map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
        </div>
        <div className="grid sm:grid-cols-3 gap-3">
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Difficulty</label>
            <select value={form.difficulty} onChange={e => update('difficulty', e.target.value)}
              className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20">
              <option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option>
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Duration</label>
            <select value={form.duration} onChange={e => update('duration', e.target.value)}
              className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20">
              <option value="1 hour">1 Hour</option><option value="2 hours">2 Hours</option><option value="3 hours">3 Hours</option>
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Total Marks</label>
            <select value={form.total_marks} onChange={e => update('total_marks', e.target.value)}
              className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20">
              <option value="40">40</option><option value="50">50</option><option value="80">80</option><option value="100">100</option>
            </select>
          </div>
        </div>
        <div>
          <label className="block text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1.5">Specific Chapters (optional)</label>
          <input value={form.chapters} onChange={e => update('chapters', e.target.value)} placeholder="e.g. Quadratic Equations, Trigonometry, Electricity..."
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20" />
        </div>
        <button onClick={generatePaper} disabled={loading}
          className="w-full flex items-center justify-center gap-2 py-3.5 rounded-xl font-bold text-sm bg-gradient-to-r from-indigo-600 to-blue-600 text-white shadow-lg disabled:opacity-50 transition-all">
          {loading ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
          {loading ? 'AI is generating your paper...' : 'Generate Question Paper'}
        </button>
      </div>

      {/* Generated Paper */}
      {paper && (
        <div className="bg-white rounded-xl border border-gray-100 shadow-[0_1px_2px_rgba(0,0,0,0.1)] overflow-hidden">
          {paper.raw ? (
            <div className="p-5"><p className="text-sm text-gray-600 whitespace-pre-wrap">{paper.raw}</p></div>
          ) : (
            <>
              <div className="bg-indigo-50 px-5 py-4 border-b border-indigo-100 flex items-center justify-between">
                <div>
                  <h2 className="font-bold text-gray-800">{paper.title}</h2>
                  <p className="text-xs text-gray-500 mt-0.5">{paper.subtitle} · Time: {paper.duration} · Max Marks: {paper.total_marks}</p>
                </div>
                <div className="flex gap-2">
                  <button onClick={downloadPDF} className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold bg-indigo-600 text-white hover:bg-indigo-700 transition-all">
                    <Download size={13} /> Download PDF
                  </button>
                  <button onClick={generatePaper} className="p-2 rounded-xl bg-gray-100 hover:bg-gray-200 transition-all"><RotateCcw size={14} className="text-gray-500" /></button>
                </div>
              </div>

              <div className="p-5 space-y-5">
                {paper.instructions?.length > 0 && (
                  <div className="bg-amber-50/60 rounded-xl p-3 border border-amber-100/50">
                    <p className="text-[10px] font-bold uppercase text-amber-600 mb-1.5">Instructions</p>
                    {paper.instructions.map((inst, i) => <p key={i} className="text-[12px] text-amber-700">{i + 1}. {inst}</p>)}
                  </div>
                )}

                {paper.sections?.map((sec, si) => (
                  <div key={si}>
                    <h3 className="font-bold text-indigo-600 text-sm mb-3 pb-1 border-b border-gray-100">{sec.name}</h3>
                    <div className="space-y-3">
                      {sec.questions?.map((q, qi) => (
                        <div key={qi} className="flex gap-3">
                          <span className="text-xs font-bold text-gray-400 w-8 flex-shrink-0 pt-0.5">Q{q.q_no}</span>
                          <div className="flex-1">
                            <p className="text-[13px] text-gray-700 leading-relaxed">{q.question}</p>
                            {q.options && (
                              <div className="grid grid-cols-2 gap-1 mt-2">{q.options.map((o, oi) => (
                                <p key={oi} className="text-[12px] text-gray-600 bg-gray-50 rounded-lg px-3 py-1.5">{o}</p>
                              ))}</div>
                            )}
                            <span className="text-[10px] text-indigo-400 font-semibold mt-1 inline-block">[{q.marks} mark{q.marks > 1 ? 's' : ''}]</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}
