const express = require('express');
const router = express.Router();
const ctrl = require('./ai.controller');
const expCtrl = require('./ai-experience.controller');
const { authenticate } = require('../../middleware/auth.middleware');

// Current Affairs
router.get('/current-affairs', authenticate, ctrl.getAICurrentAffairs);
router.get('/current-affairs/range', authenticate, ctrl.getAICurrentAffairsRange);
router.post('/current-affairs/generate', authenticate, ctrl.generateAffairs);

// Mind Map — FIXED: accepts class/board/goal, saves to DB
router.post('/mindmap', authenticate, ctrl.generateMindMap);
router.post('/mindmap/notes', authenticate, ctrl.generateMindMapNotes);
router.post('/mindmap/flowchart', authenticate, ctrl.generateFlowchart);
router.post('/mindmap/explain', authenticate, ctrl.explainWithDiagram);

// Curriculum drill-down (for mind map page)
router.get('/curriculum/subjects', authenticate, ctrl.getSubjects);
router.get('/curriculum/chapters', authenticate, ctrl.getChapters);
router.get('/curriculum/topics', authenticate, ctrl.getTopics);

// Career Guidance
router.post('/career/guidance', authenticate, ctrl.getStreamGuidance);
router.post('/career/compare', authenticate, ctrl.compareStreams);
router.post('/career/chat', authenticate, ctrl.careerChat);

// Exam Details
router.get('/exam-details', authenticate, ctrl.getAIExamDetails);

// Doubt Clearing
router.post('/doubt', authenticate, ctrl.clearDoubt);
router.post('/doubt/chat', authenticate, ctrl.doubtChat);

// AI Buddy — persistent chat
router.post('/buddy/chat', authenticate, ctrl.buddyChat);

// Chat Session Management
router.post('/chat/sessions', authenticate, ctrl.createSession);
router.delete('/chat/sessions/clear', authenticate, ctrl.clearSessions); // Clear all sessions of a type
router.delete('/chat/sessions/:sessionId', authenticate, ctrl.deleteSession);
router.put('/chat/sessions/:sessionId', authenticate, ctrl.updateSessionTitle);


// Chat History — NEW
router.get('/chat/sessions', authenticate, ctrl.getChatSessions);
router.get('/chat/sessions/:sessionId/messages', authenticate, ctrl.getChatMessages);

// AI Experience Lab
router.get('/experience/sectors', authenticate, expCtrl.getAISectors);
router.get('/experience/explore', authenticate, expCtrl.exploreProfession);
router.post('/experience/challenge', authenticate, expCtrl.generateChallenge);
router.get('/experience/comms', authenticate, expCtrl.getProfessionalComms);

// ═══ MILESTONE 2 — NEWSROOM ═══
router.get('/newsroom', authenticate, ctrl.getNewsroom);
router.post('/newsroom/generate', authenticate, ctrl.generateNewsroom);
router.post('/newsroom/expand', authenticate, ctrl.expandArticle);
router.get('/newsroom/monthly', authenticate, ctrl.getMonthlyCompilation);
router.get('/newsroom/sources', authenticate, ctrl.getNewsSources);
router.get('/newsroom/categories', authenticate, ctrl.getNewsCategories);

// ═══ MILESTONE 2 — AUTO QUIZ GENERATOR ═══
router.post('/quiz/generate-daily', authenticate, ctrl.autoGenerateDailyQuiz);
router.post('/quiz/generate-topic', authenticate, ctrl.generateTopicQuiz);
router.post('/quiz/generate-weekly', authenticate, ctrl.generateWeeklyChallenge);

// ═══ MILESTONE 2 — STREAM & FUTURE NAVIGATOR ═══
router.get('/navigator/aptitude-questions', authenticate, ctrl.getAptitudeQuestions);
router.post('/navigator/aptitude', authenticate, ctrl.submitAptitudeAssessment);
router.post('/navigator/alignment', authenticate, ctrl.generateAlignmentReport);
router.post('/navigator/roadmap', authenticate, ctrl.generateCareerRoadmap);

// ═══ MILESTONE 5 — VIRTUAL LAB ═══
router.get('/lab/subjects', authenticate, ctrl.getLabSubjects);
router.get('/lab/experiments', authenticate, ctrl.getLabExperiments);
router.post('/lab/experiment', authenticate, ctrl.generateExperiment);
router.get('/lab/visualization', authenticate, ctrl.getLabVisualization);

// ═══ MILESTONE 5 — MOCK INTERVIEW ═══
router.get('/interview/types', authenticate, ctrl.getInterviewTypes);
router.post('/interview/start', authenticate, ctrl.startInterview);
router.post('/interview/evaluate', authenticate, ctrl.evaluateInterviewAnswer);
router.post('/interview/report', authenticate, ctrl.getInterviewReport);

// ═══ MILESTONE 5 — DEBATE ARENA ═══
router.get('/debate/categories', authenticate, ctrl.getDebateCategories);
router.get('/debate/trending', authenticate, ctrl.getTrendingDebateTopics);
router.post('/debate/topic', authenticate, ctrl.generateDebateTopic);
router.post('/debate/respond', authenticate, ctrl.debateRespond);
router.post('/debate/evaluate', authenticate, ctrl.evaluateDebate);

module.exports = router;
