CREATE TABLE IF NOT EXISTS jee_questions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject_id INT UNSIGNED NOT NULL,
  chapter_id INT UNSIGNED NOT NULL,
  topic_id INT UNSIGNED,
  question_text LONGTEXT NOT NULL,
  question_image_url VARCHAR(500),
  question_type ENUM('scq','mcq','numerical','matrix_match','paragraph','assertion_reason') NOT NULL DEFAULT 'scq',
  options JSON,
  correct_answer VARCHAR(500) NOT NULL,
  solution_text LONGTEXT NOT NULL,
  solution_image_url VARCHAR(500),
  alternative_method TEXT,
  quick_trick TEXT,
  difficulty ENUM('easy','medium','hard','advanced') NOT NULL DEFAULT 'medium',
  marks INT DEFAULT 4,
  negative_marks DECIMAL(3,1) DEFAULT -1.0,
  estimated_time_seconds INT DEFAULT 180,
  source_type ENUM('pyq_main','pyq_advanced','generated','curated') NOT NULL DEFAULT 'generated',
  source_year INT,
  source_session VARCHAR(50),
  source_paper VARCHAR(50),
  concept_tags JSON,
  is_active TINYINT(1) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (subject_id) REFERENCES jee_subjects(id),
  FOREIGN KEY (chapter_id) REFERENCES jee_chapters(id),
  INDEX idx_source (source_type, source_year),
  INDEX idx_chapter_diff (chapter_id, difficulty),
  INDEX idx_subject (subject_id, question_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
