CREATE TABLE IF NOT EXISTS jee_test_attempts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  mock_test_id INT UNSIGNED NOT NULL,
  answers JSON NOT NULL,
  total_score INT NOT NULL DEFAULT 0,
  max_score INT NOT NULL DEFAULT 300,
  percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  correct_count INT NOT NULL DEFAULT 0,
  wrong_count INT NOT NULL DEFAULT 0,
  unanswered_count INT NOT NULL DEFAULT 0,
  subject_scores JSON,
  total_time_seconds INT NOT NULL DEFAULT 0,
  time_per_subject JSON,
  predicted_percentile DECIMAL(5,2),
  predicted_rank_range VARCHAR(50),
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  status ENUM('in_progress','completed','abandoned') DEFAULT 'in_progress',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (mock_test_id) REFERENCES jee_mock_tests(id),
  INDEX idx_user (user_id, completed_at DESC),
  INDEX idx_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
