'use client';
import { useState } from 'react';
import { CheckCircle2, XCircle, ChevronRight, Lightbulb, RefreshCw } from 'lucide-react';

// TODO: Questions generated by Gemini based on topic + learner's confidence level:
// gemini.generatePracticeQuestions({ topic, difficulty: learnerProfile.mathsComfort, count: 5 })
const STUB_QUESTIONS = [
  {
    id: 1,
    question: 'Which fraction is equal to 1/2?',
    options: ['1/3', '2/4', '3/5', '4/6'],
    answer: 1,
    explanation: '2/4 = 1/2 because if we divide both the top (2) and bottom (4) by 2, we get 1/2. They are equivalent fractions!',
  },
  {
    id: 2,
    question: 'A pizza is cut into 8 equal slices. You eat 2 slices. What fraction did you eat?',
    options: ['1/4', '2/6', '1/3', '2/10'],
    answer: 0,
    explanation: '2 out of 8 = 2/8. And 2/8 simplifies to 1/4 (divide both by 2). So you ate one quarter of the pizza!',
  },
  {
    id: 3,
    question: 'What is 3/6 in its simplest form?',
    options: ['2/3', '1/2', '1/3', '3/3'],
    answer: 1,
    explanation: 'Divide both 3 and 6 by their common factor 3: 3÷3=1, 6÷3=2. So 3/6 = 1/2.',
  },
  {
    id: 4,
    question: 'If 4/8 = ?/4, what is the missing number?',
    options: ['1', '2', '3', '4'],
    answer: 1,
    explanation: '4/8 = 1/2. And 2/4 = 1/2 too! So the missing number is 2.',
  },
];

export default function PracticePanel({ learnerProfile, onWrongAnswer }) {
  const [current, setCurrent] = useState(0);
  const [selected, setSelected] = useState(null);
  const [showExplanation, setShowExplanation] = useState(false);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);

  const q = STUB_QUESTIONS[current];

  const handleSelect = (idx) => {
    if (selected !== null) return;
    setSelected(idx);
    if (idx === q.answer) {
      setScore(s => s + 1);
    } else {
      onWrongAnswer?.(q.id);
    }
  };

  const handleNext = () => {
    if (current < STUB_QUESTIONS.length - 1) {
      setCurrent(c => c + 1);
      setSelected(null);
      setShowExplanation(false);
    } else {
      setDone(true);
    }
  };

  const handleReset = () => {
    setCurrent(0); setSelected(null); setShowExplanation(false); setDone(false); setScore(0);
  };

  if (done) {
    const pct = Math.round((score / STUB_QUESTIONS.length) * 100);
    return (
      <div className="bg-[#0f172a] rounded-xl p-6 border border-[#1e3a5f] text-center">
        <div className="text-5xl mb-3">
          {pct === 100 ? '🌟' : pct >= 75 ? '👍' : pct >= 50 ? '💪' : '🤗'}
        </div>
        <h3 className="text-white font-bold text-[16px] mb-1">
          {score} out of {STUB_QUESTIONS.length} correct!
        </h3>
        <p className="text-blue-200/60 text-[13px] mb-5 leading-snug">
          {pct === 100
            ? 'Perfect score! You really understand equivalent fractions.'
            : pct >= 75
            ? "Great job! Just a couple more to review."
            : "Good try! Let's go through these again — you'll get it! 💙"}
        </p>
        {/* TODO: Send score + wrong question IDs to backend for spaced repetition tracking */}
        <button
          onClick={handleReset}
          className="flex items-center gap-1.5 mx-auto px-5 py-2.5 rounded-xl bg-blue-600 text-white text-[13px] font-semibold hover:bg-blue-700"
        >
          <RefreshCw size={13} /> Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="bg-[#0f172a] rounded-xl p-4 border border-[#1e3a5f]">
      <div className="flex items-center justify-between mb-3">
        <p className="text-blue-400 text-[10px] font-bold uppercase tracking-widest">Practice</p>
        <span className="text-white/30 text-[11px]">{current + 1} / {STUB_QUESTIONS.length}</span>
      </div>

      {/* Progress track */}
      <div className="flex gap-1 mb-4">
        {STUB_QUESTIONS.map((_, i) => (
          <div key={i} className={`h-1 flex-1 rounded-full transition-all ${
            i < current ? 'bg-emerald-500'
            : i === current ? 'bg-blue-500'
            : 'bg-white/10'
          }`} />
        ))}
      </div>

      <p className="text-white text-[14px] font-medium leading-snug mb-4">{q.question}</p>

      <div className="space-y-2 mb-4">
        {q.options.map((opt, i) => {
          let cls = 'border-white/10 text-white/70 hover:border-blue-500/40 hover:bg-blue-900/20 cursor-pointer';
          if (selected !== null) {
            if (i === q.answer)           cls = 'border-emerald-500 bg-emerald-900/30 text-emerald-300 cursor-default';
            else if (i === selected)      cls = 'border-red-500 bg-red-900/30 text-red-300 cursor-default';
            else                          cls = 'border-white/5 text-white/20 cursor-default';
          }
          return (
            <button
              key={i}
              onClick={() => handleSelect(i)}
              className={`w-full text-left px-4 py-2.5 rounded-xl border text-[13px] transition-all flex items-center justify-between ${cls}`}
            >
              <span>
                <span className="font-mono text-[10px] opacity-50 mr-2">{String.fromCharCode(65 + i)}.</span>
                {opt}
              </span>
              {selected !== null && i === q.answer && <CheckCircle2 size={15} className="text-emerald-400 flex-shrink-0" />}
              {selected !== null && i === selected && i !== q.answer && <XCircle size={15} className="text-red-400 flex-shrink-0" />}
            </button>
          );
        })}
      </div>

      {selected !== null && (
        <>
          <button
            onClick={() => setShowExplanation(p => !p)}
            className="flex items-center gap-1.5 text-amber-400 text-[12px] font-medium mb-3"
          >
            <Lightbulb size={13} /> {showExplanation ? 'Hide explanation' : 'Show explanation'}
          </button>

          {showExplanation && (
            <div className="bg-amber-900/20 border border-amber-700/30 rounded-xl p-3 mb-3">
              <p className="text-amber-200 text-[12px] leading-relaxed">{q.explanation}</p>
            </div>
          )}

          <button
            onClick={handleNext}
            className="w-full py-2.5 rounded-xl bg-blue-600 text-white text-[13px] font-semibold hover:bg-blue-700 flex items-center justify-center gap-1.5"
          >
            {current < STUB_QUESTIONS.length - 1 ? 'Next Question' : 'See Results'}
            <ChevronRight size={14} />
          </button>
        </>
      )}

      {/* TODO: "More questions" → gemini.generateMoreQuestions({ topic, difficulty, wrongAnswers }) */}
    </div>
  );
}
