'use client';
import { useState } from 'react';
import { RotateCcw, ThumbsUp, ThumbsDown, Brain } from 'lucide-react';

// TODO: Flashcards generated by Gemini with spaced repetition:
// gemini.generateFlashcards({ topic, weakAreas: learnerProfile.difficultSubjects, count: 6 })
const STUB_CARDS = [
  { id: 1, front: 'What is a fraction?', back: 'A fraction shows equal parts of a whole. It is written as numerator/denominator.' },
  { id: 2, front: 'What are equivalent fractions?', back: 'Fractions that look different but have the same value. Example: 1/2 = 2/4 = 4/8.' },
  { id: 3, front: 'What does the DENOMINATOR tell you?', back: 'The bottom number — it tells you how many equal parts the whole is divided into.' },
  { id: 4, front: 'How do you simplify a fraction?', back: 'Divide both the numerator and denominator by their Greatest Common Factor (GCF).' },
  { id: 5, front: 'Is 3/4 the same as 6/8?', back: 'Yes! Multiply both 3 and 4 by 2 → 6/8. They are equivalent fractions.' },
];

export default function RevisePanel({ learnerProfile }) {
  const [cardIdx, setCardIdx] = useState(0);
  const [flipped, setFlipped]   = useState(false);
  const [known, setKnown]       = useState([]);
  const [review, setReview]     = useState([]);
  const [finished, setFinished] = useState(false);

  const card = STUB_CARDS[cardIdx];

  const nextCard = (after) => {
    setFlipped(false);
    setTimeout(() => {
      const next = cardIdx + 1;
      if (next >= STUB_CARDS.length) setFinished(true);
      else setCardIdx(next);
    }, 150);
    after();
  };

  const handleKnow   = () => nextCard(() => setKnown(k => [...k, card.id]));
  const handleReview = () => nextCard(() => setReview(r => [...r, card.id]));

  const reset = () => {
    setKnown([]); setReview([]); setCardIdx(0); setFlipped(false); setFinished(false);
  };

  if (finished) {
    return (
      <div className="bg-[#0f172a] rounded-xl p-6 border border-[#1e3a5f] text-center">
        <div className="text-4xl mb-3">🎉</div>
        <h3 className="text-white font-bold text-[15px] mb-1">Round complete!</h3>
        <div className="flex justify-center gap-6 my-4">
          <div className="text-center">
            <p className="text-emerald-400 text-[22px] font-black">{known.length}</p>
            <p className="text-white/40 text-[11px]">I know this</p>
          </div>
          <div className="text-center">
            <p className="text-amber-400 text-[22px] font-black">{review.length}</p>
            <p className="text-white/40 text-[11px]">Need review</p>
          </div>
        </div>
        <p className="text-blue-200/50 text-[12px] mb-4">
          {review.length > 0
            ? `${review.length} card(s) to review again — great awareness! 💙`
            : 'You knew them all! Excellent revision. ⭐'}
        </p>
        {/* TODO: Send known/review card IDs to backend for spaced repetition scheduling */}
        <button
          onClick={reset}
          className="flex items-center gap-1.5 mx-auto px-5 py-2.5 rounded-xl bg-purple-600 text-white text-[13px] font-semibold hover:bg-purple-700"
        >
          <RotateCcw size={13} /> Restart Deck
        </button>
      </div>
    );
  }

  return (
    <div className="bg-[#0f172a] rounded-xl p-4 border border-[#1e3a5f]">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Brain size={14} className="text-purple-400" />
          <p className="text-white text-[13px] font-semibold">Revision Flashcards</p>
        </div>
        <div className="flex items-center gap-3 text-[11px]">
          <span className="text-emerald-400 font-semibold">{known.length} ✓</span>
          <span className="text-amber-400 font-semibold">{review.length} ↻</span>
          <button onClick={reset} className="text-white/25 hover:text-white/50" title="Reset">
            <RotateCcw size={12} />
          </button>
        </div>
      </div>

      {/* Progress dots */}
      <div className="flex gap-1 mb-4">
        {STUB_CARDS.map((c, i) => (
          <div key={c.id} className={`h-1 flex-1 rounded-full transition-all ${
            known.includes(c.id)   ? 'bg-emerald-500'
            : review.includes(c.id) ? 'bg-amber-500'
            : i === cardIdx         ? 'bg-purple-500'
            : i < cardIdx           ? 'bg-white/20'
            : 'bg-white/10'
          }`} />
        ))}
      </div>

      {/* Card */}
      <div
        className="min-h-[150px] rounded-xl border border-white/10 p-5 flex flex-col items-center justify-center cursor-pointer select-none mb-4 transition-all hover:border-purple-500/40 active:scale-[0.98]"
        style={{ background: 'linear-gradient(135deg, #1e1b4b 0%, #0f172a 100%)' }}
        onClick={() => setFlipped(f => !f)}
      >
        <p className="text-[9px] font-bold uppercase tracking-widest text-white/30 mb-2">
          {flipped ? '— Answer —' : '— Question —'}
        </p>
        <p className="text-white text-[14px] font-medium leading-snug text-center">
          {flipped ? card.back : card.front}
        </p>
        {!flipped && (
          <p className="text-white/20 text-[10px] mt-4">Tap to reveal</p>
        )}
      </div>

      <p className="text-center text-white/25 text-[11px] mb-3">
        Card {cardIdx + 1} of {STUB_CARDS.length}
      </p>

      {flipped ? (
        <div className="flex gap-2">
          <button
            onClick={handleReview}
            className="flex-1 py-2.5 rounded-xl border border-amber-700/50 bg-amber-900/20 text-amber-300 text-[12px] font-semibold flex items-center justify-center gap-1.5 hover:bg-amber-900/40"
          >
            <ThumbsDown size={13} /> Need review
          </button>
          <button
            onClick={handleKnow}
            className="flex-1 py-2.5 rounded-xl border border-emerald-700/50 bg-emerald-900/20 text-emerald-300 text-[12px] font-semibold flex items-center justify-center gap-1.5 hover:bg-emerald-900/40"
          >
            <ThumbsUp size={13} /> I know this!
          </button>
        </div>
      ) : (
        <p className="text-center text-white/20 text-[11px]">Flip the card, then rate yourself honestly 😊</p>
      )}

      {/* TODO: Gemini will generate new cards targeting learner's weak areas from past sessions */}
    </div>
  );
}
