'use client';
import { useState } from 'react';
import { Sparkles, Copy, BookMarked } from 'lucide-react';

// TODO: Notes generated by Gemini: gemini.generateSmartNotes({ topic, subtopic, learnerProfile })
const STUB_NOTES = [
  {
    id: 1, type: 'definition',
    text: 'A fraction shows equal parts of a whole. The top number (numerator) says how many parts you have. The bottom (denominator) says how many equal parts the whole is divided into.',
  },
  {
    id: 2, type: 'tip',
    text: 'Equivalent fractions look different but mean the same thing. 1/2 = 2/4 = 4/8 — they all mean "half". To make them, multiply or divide both numbers by the same amount.',
  },
  {
    id: 3, type: 'memory',
    text: 'Memory trick: "De-NOMINATOR lives at the BOTTOM — it names how many parts." Think: Denominator = Down.',
  },
  {
    id: 4, type: 'example',
    text: 'Real life: A pizza cut into 8 slices — you eat 2 slices = 2/8 = 1/4. You ate one quarter of the pizza!',
  },
];

const TYPE_CONFIG = {
  definition: { bg: 'bg-blue-900/40',    border: 'border-blue-700/40',    dot: 'bg-blue-400',    label: 'Definition' },
  tip:        { bg: 'bg-emerald-900/40', border: 'border-emerald-700/40', dot: 'bg-emerald-400', label: 'Tip' },
  memory:     { bg: 'bg-amber-900/40',   border: 'border-amber-700/40',   dot: 'bg-amber-400',   label: 'Memory Aid' },
  example:    { bg: 'bg-purple-900/40',  border: 'border-purple-700/40',  dot: 'bg-purple-400',  label: 'Example' },
};

export default function SmartNotesPanel({ topic }) {
  const [copied, setCopied] = useState(null);

  const copyNote = (id, text) => {
    navigator.clipboard.writeText(text).catch(() => {});
    setCopied(id);
    setTimeout(() => setCopied(null), 1500);
  };

  return (
    <div className="bg-[#0f172a] rounded-xl p-4 border border-[#1e3a5f]">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Sparkles size={14} className="text-yellow-400" />
          <p className="text-white text-[13px] font-semibold">Smart Notes</p>
        </div>
        {/* TODO: "Save to notebook" — POST /api/ai-study/notes with note content */}
        <button className="flex items-center gap-1 text-[11px] text-blue-400 hover:text-blue-300 font-medium">
          <BookMarked size={11} /> Save all
        </button>
      </div>

      <div className="space-y-2.5">
        {STUB_NOTES.map(note => {
          const cfg = TYPE_CONFIG[note.type] || TYPE_CONFIG.definition;
          return (
            <div key={note.id} className={`${cfg.bg} ${cfg.border} border rounded-lg p-3 relative group`}>
              <div className="flex items-center gap-1.5 mb-1.5">
                <span className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${cfg.dot}`} />
                <span className="text-[9px] font-bold uppercase tracking-wider text-white/40">{cfg.label}</span>
              </div>
              <p className="text-white/80 text-[12px] leading-relaxed pr-6">{note.text}</p>
              <button
                onClick={() => copyNote(note.id, note.text)}
                className="absolute top-2.5 right-2.5 text-white/20 hover:text-white/50 opacity-0 group-hover:opacity-100 transition-opacity"
                title="Copy note"
              >
                {copied === note.id
                  ? <span className="text-[9px] text-emerald-400 font-bold">✓</span>
                  : <Copy size={11} />
                }
              </button>
            </div>
          );
        })}
      </div>

      {/* TODO: Call Gemini for more notes: gemini.generateMoreNotes({ topic, existingNotes, learnerProfile }) */}
      <button className="w-full mt-3 py-2 rounded-lg border border-blue-700/30 text-blue-400 text-[11px] font-medium hover:bg-blue-900/20 transition-colors flex items-center justify-center gap-1.5">
        <Sparkles size={11} /> Generate more notes
      </button>
    </div>
  );
}
